services:
  - type: web
    name: test-api
    env: node
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome --path /opt/render/.cache/puppeteer
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
